= DAW: Entorns de Desenvolupament, Diari de Classe
Jaume Barceló Vicens

=== 20180221

* Acabar allò que ahir vàrem deixar a mitges. Faltava fer el `git push origin master` i el 'pull request'.
* Integració del 'pull request'.
* Entre tots, fer un document que detalli tot el procés que vàrem realitzar ahir. https://docs.google.com/document/d/1s3GErY77BSrGNHkBc7JbGvyYX2hAOdFijV4WV8WNtqk/edit

=== 20180227

* Decidir dia per fer una prova.
* Neteja de branques i incorporació dels nostres propis canvis a partir del repositori upstream.
* Integració del pull request fent primer una còpia local on poder testejar els canvis.

=== 20180228

* Explicar `git rebase`. 

=== 20180306

* En Jaume em va dir que anava millorant i esperava reincorporar-se les properes setmanes.
* Recordatori prova dimarts 13.
* Fer Activitat: Documentar els rols d’integrador/mantenidor de programari i desenvolupador/contribuent

=== 20180307

* Fer Activitat: Documentar els rols d’integrador/mantenidor de programari i desenvolupador/contribuent

=== 20180313

* Prova de sistemes de control de versions. Segur que no és millor fer-la dia 20?

=== 20180314

* La prova ha anat bé. La setmana que ve donaré els resultats.
* Avui tenim l'opció de veure in video de repàs que hem vist amb l'altre grup o bé començar l'activitat de signar commits amb gpg o bé l'activitat de documentar els rols d'integrador i desenvolupador fent servir eclipse.
