= DAM: Sistemes Informàtics
Jaume Barceló Vicens

== Connexió de Sistemes en Xarxa

=== Configuració de Xarxa

Treballeu per parelles. Presenteu un únic informe consensuat amb el nom d'ambdós participants.

Esbrina quina és la teva configuració de xarxa:

* IP: Determina si és pública o privada. Escriu-la també en binari. Tracta de saber si és fixa o dinàmica. En cas d'adreça privada, esbrina quina és la teva IP pública. Compara la teva IP i la teva IP pública amb la dels companys. Què tenen en comú? En què es diferencien? Què pot passar si canviem la nostra IP? Explica les diferents possibilitats. Creus que la IP canvia si ens emportem l'ordinador a casa? Explica per què.

* Màscara: Escriu la màscara en binari. Fes servir la màscara per trobar la part de la IP que correspon a la xarxa i la part que correspon al host. Quina part coincideix amb la dels companys i quina part és diferent.

* MAC: Determina qui és el fabricant. La podem canviar? Creus que la MAC canvia si ens emportem l'ordinador a casa? Explica per què.

* Default gateway: Separa la part de xarxa de la part del host. Com ha de ser la part de xarxa comparada amb la teva?

* DNS: Pertany a la teva subxarxa? Què passaria si no tinguessim DNS?

Explica què és i per a què serveix cada un dels paràmetres de configuració: MAC, IP, NetMask, DefaultGW, DNS



