= DAM: Sistemes Informàtics, Diari de Classe
Jaume Barceló Vicens

=== 20180221

* Recordatori prova dia 20180228.
* TCP vs UDP. Avantatges/inconvenients. Quan fem servir un i quan fem servir l'altre.
* Explicar presentació.
* Acabar l'exercici de piles de protocols.

=== 20180222

* Estan corregits exercici de subnetting. 2 persones ho han tengut perfecte. Hi ha molts conceptes que encara no estan clars.
* Cal treballar un poc més el tema fins que tothom (o la gran majoria) el tengui clar.
* Preguntes subnetting.
* Corregir treball subnetting.
* Elegir quin treball voleu fer primer: capa física (cablejat estructurat) o capa d'aplicació (servidor d'acudits dolents)
* Explicar diapositives. Xarxes sense fils.

=== 20180226

* Discussió sobre contrasenyes segures. https://www.xkcd.com/936/
* Acabar d'explicar diapositives. Xarxes sense fils.

=== 20180227

* Corregits exercicis de pila de protocols
* Prova 

=== 20180227

* En Jaume m'ha dit que va millorant i que espera reincorporar-se les pròximes setmanes.
* Em falta algun exercici de pila de protocols.
* Correcció de la prova
* Quan fem la recuperació?
* Fer activitat de cablejat estructurat.

=== 20180307

* Recuperació dijous dia 8.
* Si feu una entrega fora de termini, si us plau notifiqueu-me per correu per a que jo sàpiga que la tinc pendent de corregir.
* Activitat: Connexió a xarxa amb java.

=== 20180307

* Recuperació dijous dia 8.
* Dia de la dona: Preparar i fer una presentació sobre una dona que hagi fet una contribució remarcable al món de la informàtica. Per exemple, Ada Byron, Joanna Rutkowska. Busqueu algú que penseu que ha fet una feina interessant per presentar-la als companys.
* Activitat: Connexió a xarxa amb java.

=== 20180313

* Activitat: Connexió a xarxa amb java.

=== 20180314

* Activitat: Connexió a xarxa amb java.

=== 20180314

* Activitat: Connexió a xarxa amb java.
* Recordeu incloure un fitxer README.md explicatiu. L'entrega ha de ser simplement un enllaç al repositori de github. Les instruccions per a l'usuari i la documentació relativa al desenvolupament ha de ser a l'arxiu README.md 
