= DAM: Sistemes Informàtics
Jaume Barceló Vicens

== Binari, Hexadecimal, Complement a 2

=== Activitat: Passa els següents valors decimals a binari i hexadecimal

* 0
* 15 
* 73
* 128
* 222
* 255

=== Activitat: Passa els següents valors binaris a decimal i hexadecimal

* 00000000
* 00100011
* 10101010
* 11111111

=== Activitat: Passa els següents valors hexadecimals a binari i decimal

* 0x00
* 0xAB
* 0x30
* 0xFF

=== Activitat: Passa de decimal a binari complement a 2.

* -128
* -33
* -32
* -31
* -1
* 0
* 54
* 127

=== Activitat: Passa de binari complement a 2 a decimal.

* 01010101
* 00000000
* 00000011
* 11111100
* 10000000
* 10111111

== Connexió de Sistemes en Xarxa

=== Activitat: Configuració de Xarxa

Treballeu per parelles. Presenteu un únic informe consensuat amb el nom d'ambdós participants.

Esbrina quina és la teva configuració de xarxa:

* IP: Determina si és pública o privada. Escriu-la també en binari. Tracta de saber si és fixa o dinàmica. En cas d'adreça privada, esbrina quina és la teva IP pública. Compara la teva IP i la teva IP pública amb la dels companys. Què tenen en comú? En què es diferencien? Què pot passar si canviem la nostra IP? Explica les diferents possibilitats. Creus que la IP canvia si ens emportem l'ordinador a casa? Explica per què.

* Màscara: Escriu la màscara en binari. Fes servir la màscara per trobar la part de la IP que correspon a la xarxa i la part que correspon al host. Quina part coincideix amb la dels companys i quina part és diferent.

* MAC: Determina qui és el fabricant. La podem canviar? Creus que la MAC canvia si ens emportem l'ordinador a casa? Explica per què.

* Default gateway: Separa la part de xarxa de la part del host. Com ha de ser la part de xarxa comparada amb la teva?

* DNS: Pertany a la teva subxarxa? Què passaria si no tinguéssim DNS?

Explica què és i per a què serveix cada un dels paràmetres de configuració: MAC, IP, NetMask, DefaultGW, DNS

=== Activitat: Subnetting

* Una empresa reb un assignament de IPs igual a la xarxa 3.3.3.64/27 i vol crear 3 xarxes diferents. Dues d'aquestes xarxes han de tenir dos hosts i la tercera 6 hosts. Reparteix el rang d'IPs indicant adreces de xarxa, adreces de broadcast i adreces IP de cada host. Indicau també les IPs del default GW.

* Una organització amb un rang assignat igual a 3.3.3.192/27 vol crear quatre subxarxes iguals. Indica les adreces d'aquestes xarxes, la màscara i quants dispositius podran allotjar.

* Una organització amb un rang assignat itual a 3.3.3.224/28 vol crear 3 xarxes diferents. Dues d'aquestes xarxes han de tenir 1 host i la tercera 2 hosts. Reparteix el rang d'IPs indicant adreces de xarxa, adreces de broadcast i adreces IP de cada host. Indicau també les IPs del default GW.

=== Recurs: Preguntes sobre subnetting

* Calcular tots els valors possibles d'un byte d'una màscara de xarxa.
* Calcular quantes /29 podem fer amb una /27 i altres situacions semblants.
* És possible que existeixi una *xarxa* 10.10.10.74/28? Per què? Considerar altres situacions semblants.

=== Activitat: Subnetting 2

* Una organització amb un rang assignat itual a 3.3.3.128/26 vol crear 3 xarxes diferents. Dues d'aquestes xarxes han de tenir 10 hosts i la tercera 20 hosts. Reparteix el rang d'IPs indicant adreces de xarxa, adreces de broadcast i adreces dels default gw.


=== Activitat: Piles de Protocols

Treballeu per parelles.

Explica que són la pila de protocol OSI i la pila de protocol TCP/IP. Explica amb detall cada una de les capes.

Identifica i justifica a quina capa o capes pertanyen els següents elements:

* Cable ethernet.
* Navegador web.
* Access point WiFi.
* Router.
* Connexió TCP.
* Switch.
* Proxy HTTP.
* Servidor FTP.
* Paquet UDP.
* Protocol DNS.
* Protocol ARP.
* Protocol IP.


Fes una captura amb Wireshark i busca protocols de les capes d'aplicació, transport, xarxa i enllaç.

=== Activitat: Elements d'una xarxa

Treballeu per parelles.

Explica amb detall cadascun dels següents elements de la xarxa

* Dispositiu final o host
* Servidor
* Router
* Switch
* Punt d'accés WiFi
* Servidor DHCP
* Proxy
* Servidor DNS
* Servidor Web
* Servidor de correu
* Cable ethernet
* Rack
* Patch panel
* NAS
* Firewall

=== Recurs: Llibre obert sobre xarxes "Computer Networking: Principles Protocols and Practices"

https://www.saylor.org/site/wp-content/uploads/2012/02/Computer-Networking-Principles-Bonaventure-1-30-31-OTC1.pdf

=== Activitat: Cablejat estructurat

Treballarem en grups de una, dues o tres persones.

Els edificis d'oficines disposen de cablejat per a suportar la xarxa de dades. Investiga què és el cablejat estructurat considerant aspectes com els següent.

* Tipus de cables, categories.
* Fibra monomode i fibra multimode.
* Diferents habitacions tècniques que trobem en el cablejat estructurat i la seva funcionalitat.
* Cablejat horitzontal.
* Cablejat vertical/backbone.
* Distàncies.
* Patch panel. Explicar per què és tan important.
* Rack. Espai de rack. "U", "2U", etc.
* Power over Ethernet.

Detalla quines són les fonts d'informació que has fet servir.

=== Activitat: Connexió a xarxa amb java

Llegeix l'overview:

https://docs.oracle.com/javase/tutorial/networking/overview/networking.html

I el tutorial de sockets:

https://docs.oracle.com/javase/tutorial/networking/sockets/index.html

Prova el client i el servidor d'acudits. Prova també el servidor multithread amb diferents clients de manera simultània.

* Crea el teu propi servei a Internet fent servir un servidor multi-thread.
* Fes servir git per al desenvolupament.
* Publica el teu projecte a github. Inclou un `README.md` explicatiu.
* Aquesta part es pot fer en grups d'una, dues o tres persones.

=== Activitat: Crear una NAT-network a virtualbox

Explora i explica les diferents maneres en què es pot connectar a la xarxa una màquina virtual virtualbox.

Creus que podrem connectar la nostra màquina en mode bridge a la xarxa de classe que autentica únicament adreces MAC conegudes?

Connecta dues màquines virtuals en mode NAT-network. Comprova la connexió a internet i les adreces que assigna el DHCP server. Jo he hagut de crear la xarxa amb les següents instruccions:

(Vist a https://jekewa.com/blogs/index.php/weBlog/2014/01/09/virtualbox-4-3-adds-nat)

    VBoxManage natnetwork add \
    --netname 10.20.14-NAT \
    --network "10.20.14.0/24" \
    --enable

    VBoxManage dhcpserver add \
    --netname 10.20.14-NAT \
    --ip 10.20.14.3 \
    --netmask 255.255.255.0 \
    --lowerip 10.20.14.200 \
    --upperip 10.20.14.250 \
    --enable

=== Activitat: Canviar firewall de Windows 10

=== Activitat: Compartir una carpeta a Windows 10
