= DAM: Entorns de Desenvolupament
Jaume Barceló Vicens

== Control de versions

=== Recurs: Llibre Pro Git

Aquest llibre en anglès conté tot el que necessitem per aprendre git.

https://git-scm.com/book/en/v2

=== Activitat: Familiarització amb el control de versions

Farem un treball per parelles flexibles (de 1, 2 o 3)  explicant què és el control de versions, per a què serveix, etc. Es poden posar exemples de diferents sistemes de control de versions i explicar la diferència entre els centralitzats i els distribuïts.

=== Recurs: Try Git

Aquesta web ens guiarà en una sèrie de passes bàsiques per aprendre git.

https://try.github.io/ 

=== Activitat: Guia de GitHub "Hello World"

Crea't un compte gratuït de GitHub. 

Hi ha un llistat de guies a:	
https://guides.github.com/

Nosaltres farem la guia "Hello World" per a:

* Crear un repositori.
* Crear una branca i fer-hi un commit.
* Crear un pull request
* Fer un merge del pull request.

=== Activitat: Fer un "Pull Request"

Fer un "pull request" sobre el repositori

https://github.com/jbarcelo/DAM-ED-gitexercise

canviant la línia que conté el vostre nom.

=== Activitat: Fer un pull request a un repositori del professor

=== Activitat: Git per Eclipse
